services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=secret
      - DB_NAME=order_db
