### List Orders
GET http://localhost:8080/order

### Create Order
POST http://localhost:8080/order
Content-Type: application/json

{
  "price": 100.5,
  "tax": 0.5
}

### List Orders (GraphQL)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{ listOrders { id price tax } }"
}

### Create Order (GraphQL)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation { createOrder(price: 100.5, tax: 0.5) { id price tax } }"
}
